// The selection popup's two speaker buttons.
//
// Nothing else covers this popup end to end, and its markup is now generated by
// a single `buildPopupMarkup` used for both the pending and the finished state —
// so a template that forgets a button, or speech wiring that never runs, would
// otherwise only show up in a user's hands.
const { test, expect } = require('./fixtures');
const { setExtensionSettings, openFloatBallMenu } = require('./helpers');
const http = require('http');

function startMockServer(reply) {
  return new Promise((resolve) => {
    const server = http.createServer((req, res) => {
      let body = '';
      req.on('data', (chunk) => { body += chunk; });
      req.on('end', () => {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ choices: [{ message: { content: reply } }] }));
      });
    });
    server.listen(0, '127.0.0.1', () => {
      const { port } = server.address();
      resolve({ server, endpoint: `http://127.0.0.1:${port}/v1/chat/completions` });
    });
  });
}

test('the selection popup can read out both the original and the translation', async ({ page }) => {
  const { server, endpoint } = await startMockServer('示例域名');

  try {
    await setExtensionSettings(page, {
      apiEndpoint: endpoint,
      apiKey: 'test-key',
      modelName: 'gpt-4.1-mini',
      targetLang: 'zh-CN',
      targetLangSetByUser: true,
      enableSelection: true,
      // The popup surface, not the inline one.
      selectionTranslationMode: 'popup',
    });

    await page.goto('https://example.com');
    await page.waitForSelector('#ai-translator-float-ball');

    const heading = await page.locator('h1').boundingBox();
    await page.mouse.move(heading.x + 2, heading.y + heading.height / 2);
    await page.mouse.down();
    await page.mouse.move(heading.x + heading.width - 2, heading.y + heading.height / 2, { steps: 12 });
    await page.mouse.up();

    await openFloatBallMenu(page);
    await page.click('.ai-translator-menu-item[data-action="translate-selection"]');
    await page.waitForSelector('.ai-translator-popup');

    const sourceSpeak = page.locator('.ai-translator-speak-source');
    const translationSpeak = page.locator('.ai-translator-speak-translation');

    // The original is readable straight away — it is on screen from the first
    // frame, before the request comes back.
    await expect(sourceSpeak).toBeVisible();
    // Both buttons are wired by content-speech.js, which stamps the pressed
    // state as it binds; without that stamp the click handler is not attached.
    await expect(sourceSpeak).toHaveAttribute('aria-pressed', 'false');
    await expect(sourceSpeak).toHaveAttribute('aria-label', /.+/);

    await expect(page.locator('.ai-translator-translation-text')).toContainText('示例域名');
    await expect(translationSpeak).toBeVisible();
    await expect(translationSpeak).toHaveAttribute('aria-pressed', 'false');

    // The two buttons speak different things, so they must not share a label.
    const labels = await Promise.all([
      sourceSpeak.getAttribute('aria-label'),
      translationSpeak.getAttribute('aria-label'),
    ]);
    expect(labels[0]).not.toEqual(labels[1]);
  } finally {
    server.close();
  }
});
